- name: "install packages"
  package: { name: "{{ item }}", state: "present" }
  with_items:
    - lxc

- name: "lxc | symlink"
  file: { src: "{{ role_path }}/files/{{ item }}", path: "~/{{ item }}", state: "link", force: true }
  with_items:
    - ".config/lxc"
